name: CI - Build y Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Mensaje de prueba
        run: echo "Workflow ejecutado correctamente"